var data = [
	{country: "United Arab Emirates", capital: "Abu Dhabi"},
	{country: "Nigeria", capital: "Abuja"},
	{country: "Ghana", capital: "Accra"},
	{country: "Pitcairn Islands", capital: "Adamstown"},
	{country: "Ethiopia", capital: "Addis Ababa"},
	{country: "Algeria", capital: "Algiers"},
	{country: "Niue", capital: "Alofi"},
	{country: "Jordan", capital: "Amman"},
	{country: "Netherlands", capital: "Amsterdam"},
	{country: "Andorra", capital: "Andorra la Vella"},
	{country: "Turkey", capital: "Ankara"},
	{country: "Madagascar", capital: "Antananarivo"},
	{country: "Samoa", capital: "Apia"},
	{country: "Turkmenistan", capital: "Ashgabat"},
	{country: "Eritrea", capital: "Asmara"},
	{country: "Kazakhstan", capital: "Astana"},
	{country: "Paraguay", capital: "Asunción"},
	{country: "Greece", capital: "Athens"},
	{country: "Cook Islands", capital: "Avarua"},
	{country: "Iraq", capital: "Baghdad"},
	{country: "Azerbaijan", capital: "Baku"},
	{country: "Mali", capital: "Bamako"},
	{country: "Brunei", capital: "Bandar Seri Begawan"},
	{country: "Thailand", capital: "Bangkok"},
	{country: "Central African Republic", capital: "Bangui"},
	{country: "Gambia", capital: "Banjul"},
	{country: "Saint Kitts and Nevis", capital: "Basseterre"},
	{country: "China", capital: "Beijing"},
	{country: "Lebanon", capital: "Beirut"},
	{country: "", capital: "Belfast"},
	{country: "Serbia", capital: "Belgrade"},
	{country: "Belize", capital: "Belmopan"},
	{country: "Germany", capital: "Berlin"},
	{country: "Switzerland", capital: "Bern"},
	{country: "Kyrgyzstan", capital: "Bishkek"},
	{country: "Guinea-Bissau", capital: "Bissau"},
	{country: "Colombia", capital: "Bogotá"},
	{country: "Brazil", capital: "Brasília"},
	{country: "Slovakia", capital: "Bratislava"},
	{country: "Republic of the Congo", capital: "Brazzaville"},
	{country: "Barbados", capital: "Bridgetown"},
	{country: "Belgium", capital: "Brussels"},
	{country: "Romania", capital: "Bucharest"},
	{country: "Hungary", capital: "Budapest"},
	{country: "Argentina", capital: "Buenos Aires"},
	{country: "Burundi", capital: "Bujumbura"},
	{country: "Egypt", capital: "Cairo"},
	{country: "Australia", capital: "Canberra"},
	{country: "Venezuela", capital: "Caracas"},
	{country: "Wales", capital: "Cardiff"},
	{country: "Saint Lucia", capital: "Castries"},
	{country: "French Guiana", capital: "Cayenne"},
	{country: "United States Virgin Islands", capital: "Charlotte Amalie"},
	{country: "Moldova", capital: "Chisinau"},
	{country: "Turks and Caicos Islands", capital: "Cockburn Town"},
	{country: "Guinea", capital: "Conakry"},
	{country: "Denmark", capital: "Copenhagen"},
	{country: "Senegal", capital: "Dakar"},
	{country: "Syria", capital: "Damascus"},
	{country: "Bangladesh", capital: "Dhaka"},
	{country: "East Timor (Timor-Leste)", capital: "Dili"},
	{country: "Djibouti", capital: "Djibouti"},
	{country: "Tanzania", capital: "Dodoma"},
	{country: "Qatar", capital: "Doha"},
	{country: "Isle of Man", capital: "Douglas"},
	{country: "Ireland", capital: "Dublin"},
	{country: "Tajikistan", capital: "Dushanbe"},
	{country: "Scotland", capital: "Edinburgh"},
	{country: "Tristan da Cunha", capital: "Edinburgh of the Seven Seas"},
	{country: "Sahrawi Arab Democratic Republic", capital: "El Aaiún"},
	{country: "Akrotiri and Dhekelia", capital: "Episkopi Cantonment"},
	{country: "Christmas Island", capital: "Flying Fish Cove"},
	{country: "Sierra Leone", capital: "Freetown"},
	{country: "Tuvalu", capital: "Funafuti"},
	{country: "Botswana", capital: "Gaborone"},
	{country: "Cayman Islands", capital: "George Town"},
	{country: "Ascension Island", capital: "Georgetown"},
	{country: "Guyana", capital: "Georgetown"},
	{country: "Gibraltar", capital: "Gibraltar"},
	{country: "South Georgia and the South Sandwich Islands", capital: "Grytviken"},
	{country: "Guatemala", capital: "Guatemala City"},
	{country: "Saint Barthélemy", capital: "Gustavia"},
	{country: "Guam", capital: "Hagåtña"},
	{country: "Bermuda", capital: "Hamilton"},
	{country: "Easter Island", capital: "Hanga Roa"},
	{country: "Vietnam", capital: "Hanoi"},
	{country: "Zimbabwe", capital: "Harare"},
	{country: "Somaliland", capital: "Hargeisa"},
	{country: "Cuba", capital: "Havana"},
	{country: "Finland", capital: "Helsinki"},
	{country: "Solomon Islands", capital: "Honiara"},
	{country: "Pakistan", capital: "Islamabad"},
	{country: "Indonesia", capital: "Jakarta"},
	{country: "Saint Helena", capital: "Jamestown"},
	{country: "Israel", capital: "Jerusalem"},
	{country: "State of Palestine", capital: "Ramallah"},
	{country: "South Sudan", capital: "Juba"},
	{country: "Afghanistan", capital: "Kabul"},
	{country: "Uganda", capital: "Kampala"},
	{country: "Nepal", capital: "Kathmandu"},
	{country: "Sudan", capital: "Khartoum"},
	{country: "Ukraine", capital: "Kiev"},
	{country: "Rwanda", capital: "Kigali"},
	{country: "Jamaica", capital: "Kingston"},
	{country: "Norfolk Island", capital: "Kingston"},
	{country: "Saint Vincent and the Grenadines", capital: "Kingstown"},
	{country: "Democratic Republic of the Congo", capital: "Kinshasa"},
	{country: "Malaysia", capital: "Kuala Lumpur"},
	{country: "Kuwait", capital: "Kuwait City"},
	{country: "Gabon", capital: "Libreville"},
	{country: "Malawi", capital: "Lilongwe"},
	{country: "Peru", capital: "Lima"},
	{country: "Portugal", capital: "Lisbon"},
	{country: "Slovenia", capital: "Ljubljana"},
	{country: "Togo", capital: "Lomé"},
	{country: "United Kingdom", capital: "London"},
	{country: "Angola", capital: "Luanda"},
	{country: "Zambia", capital: "Lusaka"},
	{country: "Luxembourg", capital: "Luxembourg"},
	{country: "Spain", capital: "Madrid"},
	{country: "Marshall Islands", capital: "Majuro"},
	{country: "Equatorial Guinea", capital: "Malabo"},
	{country: "Maldives", capital: "Malé"},
	{country: "Nicaragua", capital: "Managua"},
	{country: "Bahrain", capital: "Manama"},
	{country: "Philippines", capital: "Manila"},
	{country: "Mozambique", capital: "Maputo"},
	{country: "Saint Martin", capital: "Marigot"},
	{country: "Lesotho", capital: "Maseru"},
	{country: "Wallis and Futuna", capital: "Mata-Utu"},
	{country: "Swaziland", capital: "Lobamba"},
	{country: "Palau", capital: "Melekeok"},
	{country: "Mexico", capital: "Mexico City"},
	{country: "Belarus", capital: "Minsk"},
	{country: "Somalia", capital: "Mogadishu"},
	{country: "Monaco", capital: "Monaco"},
	{country: "Liberia", capital: "Monrovia"},
	{country: "Uruguay", capital: "Montevideo"},
	{country: "Comoros", capital: "Moroni"},
	{country: "Russia", capital: "Moscow"},
	{country: "Oman", capital: "Muscat"},
	{country: "Kenya", capital: "Nairobi"},
	{country: "Bahamas", capital: "Nassau"},
	{country: "Myanmar", capital: "Naypyidaw"},
	{country: "Chad", capital: "N'Djamena"},
	{country: "India", capital: "New Delhi"},
	{country: "Niger", capital: "Niamey"},
	{country: "Cyprus", capital: "Nicosia"},
	{country: "Northern Cyprus", capital: "Nicosia"},
	{country: "Mauritania", capital: "Nouakchott"},
	{country: "New Caledonia", capital: "Nouméa"},
	{country: "Tonga", capital: "Nukuʻalofa"},
	{country: "Greenland", capital: "Nuuk"},
	{country: "Aruba", capital: "Oranjestad"},
	{country: "Norway", capital: "Oslo"},
	{country: "Canada", capital: "Ottawa"},
	{country: "Burkina Faso", capital: "Ouagadougou"},
	{country: "American Samoa", capital: "Pago Pago"},
	{country: "Federated States of Micronesia", capital: "Palikir"},
	{country: "Panama", capital: "Panama City"},
	{country: "French Polynesia", capital: "Papeete"},
	{country: "Suriname", capital: "Paramaribo"},
	{country: "France", capital: "Paris"},
	{country: "Sint Maarten", capital: "Philipsburg"},
	{country: "Cambodia", capital: "Phnom Penh"},
	{country: "Montserrat", capital: "Plymouth"},
	{country: "Montenegro", capital: "Podgorica"},
	{country: "Mauritius", capital: "Port Louis"},
	{country: "Papua New Guinea", capital: "Port Moresby"},
	{country: "Vanuatu", capital: "Port Vila"},
	{country: "Haiti", capital: "Port-au-Prince"},
	{country: "Trinidad and Tobago", capital: "Port of Spain"},
	{country: "Cotonou", capital: "Porto-Novo"},
	{country: "Czech Republic", capital: "Prague"},
	{country: "Cape Verde", capital: "Praia"},
	{country: "South Africa", capital: "Pretoria"},
	{country: "Kosovo", capital: "Pristina"},
	{country: "North Korea", capital: "Pyongyang"},
	{country: "Ecuador", capital: "Quito"},
	{country: "Morocco", capital: "Rabat"},
	{country: "Iceland", capital: "Reykjavík"},
	{country: "Latvia", capital: "Riga"},
	{country: "Saudi Arabia", capital: "Riyadh"},
	{country: "British Virgin Islands", capital: "Road Town"},
	{country: "Italy", capital: "Rome"},
	{country: "Dominica", capital: "Roseau"},
	{country: "Northern Mariana Islands", capital: "Saipan"},
	{country: "Costa Rica", capital: "San José"},
	{country: "Puerto Rico", capital: "San Juan"},
	{country: "San Marino", capital: "San Marino"},
	{country: "El Salvador", capital: "San Salvador"},
	{country: "Yemen", capital: "Sanaá"},
	{country: "Chile", capital: "Santiago"},
	{country: "Dominican Republic", capital: "Santo Domingo"},
	{country: "São Tomé and Príncipe", capital: "São Tomé"},
	{country: "Bosnia and Herzegovina", capital: "Sarajevo"},
	{country: "South Korea", capital: "Seoul"},
	{country: "Singapore", capital: "Singapore"},
	{country: "Macedonia", capital: "Skopje"},
	{country: "Bulgaria", capital: "Sofia"},
	{country: "Sri Lanka", capital: "Sri Jayawardenapura-Kotte"},
	{country: "Grenada", capital: "St. George's"},
	{country: "Jersey", capital: "St. Helier"},
	{country: "Antigua and Barbuda", capital: "St. John's"},
	{country: "Guernsey", capital: "St. Peter Port"},
	{country: "Saint Pierre and Miquelon", capital: "St. Pierre"},
	{country: "Falkland Islands", capital: "Stanley"},
	{country: "Nagorno-Karabakh Republic", capital: "Stepanakert"},
	{country: "Sweden", capital: "Stockholm"},
	{country: "Bolivia", capital: "La Paz"},
	{country: "Abkhazia", capital: "Sukhumi"},
	{country: "Fiji", capital: "Suva"},
	{country: "Taiwan", capital: "Taipei"},
	{country: "Estonia", capital: "Tallinn"},
	{country: "Kiribati", capital: "Tarawa"},
	{country: "Uzbekistan", capital: "Tashkent"},
	{country: "Georgia", capital: "Tbilisi"},
	{country: "Honduras", capital: "Tegucigalpa"},
	{country: "Iran", capital: "Tehran"},
	{country: "Bhutan", capital: "Thimphu"},
	{country: "Albania", capital: "Tirana"},
	{country: "Transnistria", capital: "Tiraspol"},
	{country: "Japan", capital: "Tokyo"},
	{country: "Faroe Islands", capital: "Tórshavn"},
	{country: "Libya", capital: "Tripoli"},
	{country: "South Ossetia", capital: "Tskhinvali"},
	{country: "Tunisia", capital: "Tunis"},
	{country: "Mongolia", capital: "Ulan Bator"},
	{country: "Liechtenstein", capital: "Vaduz"},
	{country: "Malta", capital: "Valletta"},
	{country: "Anguilla", capital: "The Valley"},
	{country: "Vatican City", capital: "Vatican City"},
	{country: "Seychelles", capital: "Victoria"},
	{country: "Austria", capital: "Vienna"},
	{country: "Laos", capital: "Vientiane"},
	{country: "Lithuania", capital: "Vilnius"},
	{country: "Poland", capital: "Warsaw"},
	{country: "United States", capital: "Washington, D.C."},
	{country: "New Zealand", capital: "Wellington"},
	{country: "Cocos (Keeling) Islands", capital: "West Island"},
	{country: "Curaçao", capital: "Willemstad"},
	{country: "Namibia", capital: "Windhoek"},
	{country: "Ivory Coast", capital: "Yamoussoukro"},
	{country: "Cameroon", capital: "Yaoundé"},
	{country: "Nauru", capital: "Yaren"},
	{country: "Armenia", capital: "Yerevan"},
	{country: "Croatia", capital: "Zagreb"}
];